# https://taskfile.dev

version: '3'

vars:
  PAYLOAD_FOLDER: payloads
  CURRENT_USER: 
    sh: echo "$(whoami)"

tasks:
  default:
    cmds:
      - echo "Run task --list for usage."
    silent: true
  payload_folder:
    desc: "Setup payload folder"
    cmds:
      - mkdir {{.PAYLOAD_FOLDER}}
      - sudo chown nobody:{{.CURRENT_USER}} -R {{.PAYLOAD_FOLDER}}
      - sudo chmod -R 777 {{.PAYLOAD_FOLDER}}
  printnightmare_samba_share:
    desc: "Setup Samba smb.conf for printnightmare "
    cmds:
      - sudo cp smb.conf /etc/samba/smb.conf
      - echo 'Update the share path in /etc/samba/smb.conf to match the payload folder and run service smbd restart'
  restore_samba:
    desc: "Restore Samba"
    cmds:
      - sudo cp smb.conf.backup /etc/samba/smb.conf
      - sudo service smbd stop
